def REVC(s:str)->str:
    s = s[::-1]
    rep_dict = {"A":"T","T":"A","C":"G","G":"C"}
    return "".join([rep_dict.get(i) for i in s])

if __name__ == '__main__':
    with open("rosalind_revc.txt") as text_file:
        example = text_file.read().strip()
    print(REVC(example))


# Expected Answer
# ACGACATACTGACCCGTTTTAGCCTGCGAAGATTGTCCATTCAGATCCGCGACAATATAAGGCCCACGAATTTACATATGTCATCGTCTTGTAGGTAGACAGTGTTCCCCTTACACGTCCCTAAGATCCAGCTCCCATTCCGGTTCTGGAATACTGTTATGCGCTTGCTGGGCAGCAACATGGTCACGCATAGTGCTACCACATACTGTGGCATGGGACCTCCACCAGTGCGTCGTACCACTCGAACCTGATAACAACGTGCTTTGGCTACGTCGCCTCAGTCAGATTAGCGACATGGGATGCGGCGTACAGCGTGATTTCCTCTTGTCCGCGTCATCTAATAACGTGTGTAGTAGACCGGAGCATCCTGTGATTGACAGGAAGATCCAGCAACCCGCAACCTGACACTGCTTGCACATCGTAGCGCCTTTCGGTACCTTGTTAGTCCCTAAGTTATTTCTTGCCCAAACGCTGGCACGTGGAAGCTTAGCGTTTATGCGACGGGCATCAGTCCGGGTTCAAGACCTAGCACTACCAGGACGCTAGCCTACTTAATTTAGCCCGGCCGAGAAGATTGGCCTGCTAGCCAACTTGAGGTTAATCCCTTACATAGGGCACTCGCCAATCCCGCGAATACAGGTCAGGCTAAAATTATACTTAGCGCATCGGATAATGGCAGTAGACTGTCCGCGCATTCACAGCAGTGACGCCTGCCCGCGCGACGTGAGCGGTGAGATCCCCAATGACGACGAGCACCCCATTCGTCATGCATGCTTATATTGTTCCAGCGGAGCAGGATCCTTTTCGAATAGC